### ISSUE TITLE
ALED-2009 setting dim levels

### ISSUE THREAD

**Issue by marathonworks** [robertklep/homebridge-klikaanklikuit#5]
I've resurrected my old KaKu set and it works great! Nice job on this plugin. So great I also wanted to try the LED lamp for precise dimming. But after I've configured it, something weird is happening..

When changing to a new DIM setting on de ALED-2009, using the moving slider in the Home App, the lamp will often turn itself off. Only after switching it back on, the light appears to have the right setting.

I was looking at your code and noticed the 2 seconds delay before you can send another ON. This sounds correct. Is there a similar setting for switching it off? 

Ps. When my lamp is turned off but the power is still on, I hear a high pitched sound...anyone noticed something similar?

**Comment by robertklep** [comment]
@marathonworks dimming is a bit of a PITA to be honest.

There's two ways you can dim the ALED-2009 (which I have myself), either by sending a _"dim to level X"_ command to it, or by putting it into "dimming mode" by sending the ON command twice within a certain amount of time.

Since this plugin only supports the first (_"dim to level X"_) command, I've tried to disable putting the device into dimming mode by disallowing the ON command to be sent more than once every two seconds (which may be too short of a time, I haven't really tested it very well). Since the lamp doesn't have an equivalent based on the OFF command, there's no need to rate limit those.

HomeKit issues brightness actions (the one that gets send when you use the slider) without (at least, I think) waiting for the backend to actually handle it. So you may end up with multiple brightness actions being processed at the same time, causing erratic behaviour. I've noticed the same issue.

If I have some time tomorrow, I'll try and investigate why the lamp isn't responding properly. Perhaps it's as easy as debouncing incoming actions (which is similar to what it already does with the ON command).

**Comment by marathonworks** [comment]
Hi Robert, thx for explaining the code and how the ALED works. I'm happy to test along.. I did some research on another dimmer.

Dimming the Outlet/Switch ACD-300 works very well with the current code. It doesn't turn of the light while setting new dim levels. Apparently the ALED-2009 works with a different sequence. 

Is there a gesture trigger in the "Home" app when you release the slider? Perhaps we can catch that moment and send a new dim setting.. just a thought.

Dankjewel for the fast response! :-)

**Comment by robertklep** [comment]
@marathonworks I just found that the ALED doesn't seem to care about the time in between ON commands, even if they are more than 10 seconds apart, it still switches to dimming mode. So I'll start by just not accepting multiple successive ON commands for dimmable devices.

**Comment by robertklep** [comment]
@marathonworks just pushed a new version to Github, it seems to work better now.

If you care to try, you can install it directly from GH:

```
$ sudo npm i -g robertklep/homebridge-klikaanklikuit
```

(the `sudo` might be optional, depending on your setup)

**Comment by marathonworks** [comment]
Great stuff, I'll test it tonight, keep you posted!

**Comment by marathonworks** [comment]
I've tested the new version. Dimming the ALED-2009 is much more stable now. Occasionally the LED is unresponsive, but resending dim commands fixes this. It doesn't turn itself off anymore. This is definitely workable, thx!

**Comment by robertklep** [comment]
Thanks for testing, I just published it as v1.2.0! Closing this issue for now :)
